<?php
/**
 * Страница "Форма настройки Даты и Времени".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Date and Time setting form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form for setting the date and time can be called from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>"Configuration / System" partition bar;</li>
        <li>start, item "Configuration".</li>
    </ul>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Date format.</b> The date input and output format is set for all form fields and Control Panel list columns;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Time format.</b> The time input and output format is set for all form fields and Control Panel list columns;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Reset settings.</b> Resets all settings to default values ​​if the flag is set (only after pressing the "Save" button).</li>
    </ul>
</article>