<?php
/**
 * Страница "Форма настройки Даты и Времени".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Date and Time setting form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form for setting the date and time can be called from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>"Configuration / System" partition bar;</li>
        <li>start, item "Configuration".</li>
    </ul>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Date format.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Time format.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Reset settings.</b> Resets all settings to default values (only after pressing the "Save" button).</li>
    </ul>
</article>